version: "3.8"

services:
  # Postgres Database
  database:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: shareboard
      POSTGRES_PASSWORD: shareboard
      POSTGRES_DB: shareboard
    volumes:
      - pgdata:/var/lib/postgresql/data

  # NestJS Services
  services:
    build:
      dockerfile: Dockerfile
      context: ./services
    environment: 
      DATABASE_URL: 'postgresql://shareboard:shareboard@database:5432/shareboard?sslmode=disable'
    ports:
      - 3000:3000
    links:
      - database
  
  # React Webapp
  webapp:
    build:
      dockerfile: Dockerfile
      context: ./webapp
      args:
        REACT_APP_SERVICE_URL: 'http://localhost:3000'
    ports:
      - 4200:80
    links:
      - services

volumes:
  pgdata: